# Generated by Django 3.2.6 on 2021-09-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxAbbreviations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True)),
                ('abbreviation', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=100)),
                ('temporality', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(blank=True, max_length=100)),
                ('temporality', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrontCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_abbreviation', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PublicWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=11)),
                ('office', models.CharField(blank=True, max_length=100)),
                ('class_worker', models.CharField(blank=True, max_length=100)),
                ('capacity', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelfe_number', models.IntegerField(blank=True)),
                ('shelfp_number', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed', models.BooleanField(blank=True)),
                ('eliminated', models.BooleanField(blank=True)),
                ('sent_from', models.CharField(blank=True, max_length=100)),
                ('requested_document', models.CharField(blank=True, max_length=100)),
                ('send_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unity_name', models.CharField(blank=True, max_length=100)),
                ('unity_abbreviation', models.CharField(blank=True, max_length=20)),
                ('administrative_bond', models.CharField(blank=True, max_length=100)),
                ('bond_abbreviation', models.CharField(blank=True, max_length=20)),
                ('type_of_unity', models.CharField(blank=True, max_length=30)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('telephone_number', models.CharField(blank=True, max_length=8)),
                ('note', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
