# Generated by Django 3.2.6 on 2021-10-28 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencysheet',
            name='person_name',
        ),
        migrations.AddField(
            model_name='frequencysheet',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archives_app.publicworker'),
        ),
    ]
