# Generated by Django 3.2.6 on 2021-09-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelfe_number', models.IntegerField(blank=True)),
                ('shelfp_number', models.IntegerField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ShelfE',
        ),
        migrations.DeleteModel(
            name='ShelfP',
        ),
    ]
